routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{

    DashboardController,
    CompanyController,
    EmploeyController,
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



require __DIR__.'/auth.php';


Route::group([
    'prefix'=>'dashboard',
    'middleware'=>['auth', 'admin'],
    'as'=> 'dashboard.'
    ],function() {
        Route::get('/', [DashboardController::class, 'index'])->name('index');

        Route::resources([
            'companies' => CompanyController::class,
        ]);
        Route::resources([
            'employees' => EmploeyController::class,
        ]);


});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $fillable = [
        'name',
        'email',
        'website',
        'logo'
    ];

    public function employees() {
        return $this->hasMany(Emploey::class);
    }
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Company\AddNewCompany;
use App\Models\Company;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $companies = Company::latest()->paginate(10);
        return view('admin.companies.companies', compact('companies'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('admin.companies.create_company');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(AddNewCompany $request)
    {
        //

        $validated = $request->validated();
        $company = new Company();
        $company->name = $request->name;
        $company->email = $request->email;
        $company->website = $request->website;
        if(!empty($request->company_image)){
            $company->logo = $request->company_image->getClientOriginalName();
        }
        $company->save();
        $destination= 'public/Company'.$company->id;
        if(!empty($request->company_image)){
            $request->company_image->storeAs($destination,$request->company_image->getClientOriginalName());
        }
        return redirect()->route('dashboard.companies.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        //

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request)
    {
        //

        $company = Company::findOrFail($request->id);
        $company->name = $request->name;
        $company->email = $request->email;
        $company->website = $request->website;
        if(!empty($request->company_image)){
            $destination= 'public/Company'.$request->id.'/'.$company->logo;
            Storage::delete($destination);
            $company->logo = $request->company_image->getClientOriginalName();
        }
        $company->save();
        $destination= 'public/Company'.$company->id;
        if(!empty($request->company_image)){
            $request->company_image->storeAs($destination,$request->company_image->getClientOriginalName());
        }
        return redirect()->route('dashboard.companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request)
    {
        //
        $company = Company::findOrFail($request->id);
        $destination= 'public/Company'.$request->id;
        Storage::deleteDirectory($destination);
        $company->delete();
        return redirect()->route('dashboard.companies.index');
    }
}

resources/views/admin/companies/companies.blade.php
@extends('admin.master')
@section('navbar-title', 'الشركات')

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize pe-3">جدول الشركات</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
            <div class="button_datatable px-2">
                <a href="{{route('dashboard.companies.create')}}" class="btn btn-success text-sm" id="add_new_user_button" type="button">
                    <i class="fa fa-plus"></i>
                    إضافة شركة جديد
                </a>

            </div>
            <div class="table-responsive p-0">
                <table class="table align-items-center mb-0 table-hover " style="width:100%">
                <thead>
                    <tr>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">الأسم</th>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">الإيميل</th>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">الموقع الإلكتروني</th>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7"> الصورة </th>
                    <th class="text-secondary text-secondary text-s font-weight-bolder opacity-7">الاجراءات</th>
                    </tr>
                </thead>
                @foreach($companies as $company)
                    <tr>
                        <td>{{$company->name}}</td>
                        <td>
                            @if ($company->email)
                                {{$company->email}}
                            @else
                                لا يوجد
                            @endif

                        </td>
                        <td>
                            @if ($company->website)
                                {{$company->website}}
                            @else
                                لا يوجد
                            @endif
                        </td>
                        <td>
                            @if ($company->logo)
                                <img src="{{ url('storage/'.'Company'.$company->id.'/'.$company->logo) }}" style="width: 75px; height: 75px ; border-radius: 50%; object-fit: cover" alt="alt">
                            @else
                                لا يوجد
                            @endif
                        </td>
                        <td>
                            {{-- Start For Edite --}}
                            <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#edite{{ $company->id }}">
                                تعديل
                            </button>
                              <!-- Modal -->
                              <div class="modal fade" id="edite{{ $company->id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title text-center" id="staticBackdropLabel">تعديل معلومات الشركة</h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form enctype="multipart/form-data" method="POST" action="companies/{{ $company->id }}" class="text-end ">
                                            @csrf
                                            @method('PUT')
                                            <input type="hidden" name="id" value="{{ $company->id }}">
                                            <div class="row align-items-center">
                                                <div class="col-12">
                                                    <div class="input-group input-group-outline  is-focused my-1 is-focused">
                                                        <label class="form-label">الأسم</label>
                                                        <input name="name" id="name" type="text" required value="{{ $company->name }}"  class="form-control">
                                                    </div>
                                                    @error('name')
                                                        <div class="alert alert-danger">{{ $message }}</div>
                                                    @enderror
                                                </div>
                                            </div>
                                            <div class="row align-items-center">
                                                <div class="col-12">
                                                    <div class="input-group input-group-outline  is-focused my-1">
                                                        <label class="form-label">الايميل</label>
                                                        <input name="email" id="email" value="{{ $company->email }}" type="email" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="row align-items-center">
                                                <div class="col-12">
                                                    <div class="input-group input-group-outline  is-focused my-1">
                                                        <label class="form-label">الموقع</label>
                                                        <input id="website" name="website" value="{{ $company->website}}" type="text" class="form-control">
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="d-flex justify-content-center">
                                                @if ($company->logo)
                                                    <img src="{{ url('storage/'.'Company'.$company->id.'/'.$company->logo) }}" style="width: 75px; height: 75px ; border-radius: 50%; object-fit: cover" alt="alt">
                                                @else
                                                    <p class="fw-bold m-3">لا يوجد صورة</p>
                                                @endif
                                            </div>
                                            <div class="input-group mb-3">
                                                <input type="file" class="form-control" name="company_image" accept="image/*" id="inputGroupFile02">
                                                <label class="input-group-text" for="inputGroupFile02">Upload</label>
                                              </div>

                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
                                      <button type="submit" class="btn btn-primary">حفظ التعديلات</button>
                                    </div>
                                </form>
                                  </div>
                                </div>
                              </div>
                            {{-- End For Edite --}}
                            {{-- Start For Delete --}}
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#delete{{ $company->id }}">
                                حذف
                            </button>
                            <div class="modal fade" id="delete{{ $company->id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title text-center" id="staticBackdropLabel">حذف معلومات الشركة</h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form enctype="multipart/form-data" method="POST" action="companies/{{ $company->id }}" class="text-end ">
                                            @csrf
                                            @method('delete')
                                            <input type="hidden" name="id" value="{{ $company->id }}">
                                            <h4 class="text-black">هل أنت متأكد؟</h4>
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
                                      <button type="submit" class="btn btn-primary"> حذف</button>
                                    </div>
                                </form>
                                  </div>
                                </div>
                              </div>
                            {{-- End For Delete --}}
                        </td>
                    </tr>
                @endforeach
                </table>
                {{ $companies->links() }}
            </div>
        </div>
      </div>
    </div>
  </div>

  <!--     toast start     -->
  <div class="position-fixed top-0 start-0 p-lg-3" style="z-index: 11">
    <div class="toast fade hide p-2 mt-2 bg-gradient-info" role="alert" aria-live="assertive" id="infoToast" aria-atomic="true">
        <div class="toast-header bg-transparent border-0">
          <i class="material-icons text-white ms-2">notifications</i>
          <span class="ms-auto text-white font-weight-bold text-lg">اشعار</span>
          <i class="fas fa-times text-md text-white me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal light m-0">
        <div class="toast-body text-white text-lg">
          يتم الآن الحذف ....
        </div>
      </div>

      <div class="toast fade hide p-2 bg-white" role="alert" aria-live="assertive" id="successToast" aria-atomic="true">
        <div class="toast-header border-0">
          <i class="material-icons text-success ms-2">check</i>
          <span class="ms-auto font-weight-bold text-lg">نجاح</span>
          <i class="fas fa-times text-md me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal dark m-0">
        <div class="toast-body text-lg">
         تمت العملية بنجاح
        </div>
      </div>

  </div>
  <!--     toast end     -->

@endsection

resources/views/admin/companies/create_company.blade.php
@extends('admin.master')
@section('navbar-title', 'إضافة شركة')

@section('content')
<div class="row">
    <div class=" col-12">
        <div class="card">
            <div class="card-header pb-0  px-3 ">
                <h6 class="mb-0 text-lg">إضافة شركة جديدة</h6>
            </div>

            <div class="card-body pt-2 px-3">

                <div style="display: none" class="alert alert-danger alert-dismissible text-white" role="alert" id="alert_message">
                    <span class="text-sm"></span>
                    <ul class="text-sm m-0" id="errors_list"></ul>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <script>
                    $("#alert_message").on("close.bs.alert", function () {
                        // hide the alert >>> not remove it
                        $("#alert_message").hide();
                        return false;
                    });
                </script>

                <form enctype="multipart/form-data" method="POST" action="{{ route("dashboard.companies.store") }}" class="text-end ">
                    @csrf

                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1">
                                <label class="form-label">الأسم</label>
                                <input name="name" id="name" type="text"   class="form-control">
                            </div>
                            @error('name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1">
                                <label class="form-label">الايميل</label>
                                <input name="email" id="email" value="{{ old('email') }}" type="email" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1">
                                <label class="form-label">الموقع</label>
                                <input id="website" name="website" value="{{ old('website') }}" type="text" class="form-control">
                            </div>
                        </div>
                    </div>

                    {{-- <div class="input-group input-group-outline mb-3">
                        <input id="company_image" name="company_image" type="file" class="form-control">
                    </div> --}}
                    <div class="input-group mb-3">
                        <input type="file" class="form-control" name="company_image" accept="image/*" id="inputGroupFile02">
                        <label class="input-group-text" for="inputGroupFile02">Upload</label>
                      </div>

                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-primary w-50 my-4 mb-2 text-lg">
                        <span id="button_submit_text">إضافة</span>
                      </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>



<script>
    // Get a reference to the file input element
    const inputElement = document.querySelector('input[id="company_image"]');

    // Create a FilePond instance
    const pond = FilePond.create(inputElement);

    FilePond.setOptions({
    server: {
        url : '/company_image',
        headers: {'X-CSRF-TOKEN': '{{ csrf_token() }}'},
    }
    });
</script>







@endsection