routes/web.php
<?php

use App\Http\Controllers\ProfileController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\{

    DashboardController,
    CompanyController,
    EmploeyController,
};

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});



require __DIR__.'/auth.php';


Route::group([
    'prefix'=>'dashboard',
    'middleware'=>['auth', 'admin'],
    'as'=> 'dashboard.'
    ],function() {
        Route::get('/', [DashboardController::class, 'index'])->name('index');

        Route::resources([
            'companies' => CompanyController::class,
        ]);
        Route::resources([
            'employees' => EmploeyController::class,
        ]);


});

resources/views/admin/employees/create_emploey.blade.php
@extends('admin.master')
@section('navbar-title', 'إضافة موظف')

@section('content')
<div class="row">
    <div class=" col-12">
        <div class="card">
            <div class="card-header pb-0  px-3 ">
                <h6 class="mb-0 text-lg">إضافة موظف جديد</h6>
            </div>

            <div class="card-body pt-2 px-3">

                <div style="display: none" class="alert alert-danger alert-dismissible text-white" role="alert" id="alert_message">
                    <span class="text-sm"></span>
                    <ul class="text-sm m-0" id="errors_list"></ul>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form enctype="multipart/form-data" method="POST" action="{{ route("dashboard.employees.store") }}" class="text-end ">
                    @csrf

                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1">
                                <label class="form-label">الأسم الأول</label>
                                <input name="first_name" id="first_name" type="text"   class="form-control">
                            </div>
                            @error('first_name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1">
                                <label class="form-label">الأسم الأخير</label>
                                <input name="last_name" id="last_name" type="text"   class="form-control">
                            </div>
                            @error('last_name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1">
                                <label class="form-label">الايميل</label>
                                <input name="email" id="email" value="{{ old('email') }}" type="email" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <select class="form-select form-select-lg mb-3"  name="company_id" aria-label=".form-select-lg example">
                                <option value="" selected>Chose Company</option>
                                @foreach ($companies as $company)
                                    <option value="{{ $company->id }}">{{ $company->name }}</option>
                                @endforeach
                              </select>
                              @error('company_id')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1">
                                <label class="form-label">رقم الهاتف</label>
                                <input id="phone" name="phone" value="{{ old('phone') }}" type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-primary w-50 my-4 mb-2 text-lg">
                        <span id="button_submit_text">إضافة</span>
                      </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/employees/edite_emploey.blade.php
@extends('admin.master')
@section('navbar-title', 'تعديل موظف')

@section('content')
<div class="row">
    <div class=" col-12">
        <div class="card">
            <div class="card-header pb-0  px-3 ">
                <h6 class="mb-0 text-lg">تعديل معلومات الموظف</h6>
            </div>

            <div class="card-body pt-2 px-3">

                <div style="display: none" class="alert alert-danger alert-dismissible text-white" role="alert" id="alert_message">
                    <span class="text-sm"></span>
                    <ul class="text-sm m-0" id="errors_list"></ul>
                    <button type="button" class="btn-close text-lg py-3 opacity-10" data-bs-dismiss="alert" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <form  method="POST" action="/dashboard/employees/{{ $emploey->id }}" class="text-end ">
                    @csrf
                    @method('PUT')
                    <input type="hidden" name="id" value="{{ $emploey->id }}">
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1 is-focused ">
                                <label class="form-label">الأسم الأول</label>
                                <input name="first_name" value="{{ $emploey->first_name }}" id="first_name" type="text"   class="form-control">
                            </div>
                            @error('first_name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1 is-focused">
                                <label class="form-label">الأسم الأخير</label>
                                <input name="last_name" value="{{ $emploey->last_name }}" id="last_name" type="text"   class="form-control">
                            </div>
                            @error('last_name')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1 is-focused">
                                <label class="form-label">الايميل</label>
                                <input name="email" id="email" value="{{ $emploey->email }}" type="email" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <select class="form-select form-select-lg mb-3"  name="company_id" aria-label=".form-select-lg example">
                                <option value="">Chose Company</option>
                                @foreach ($companies as $company)
                                    <option
                                        @if ($company->id == $emploey->company_id)
                                            selected
                                        @endif
                                    value="{{ $company->id }}">{{ $company->name }}</option>
                                @endforeach
                              </select>
                              @error('company_id')
                                <div class="alert alert-danger">{{ $message }}</div>
                            @enderror
                        </div>
                    </div>
                    <div class="row align-items-center">
                        <div class="col-md-6 col-lg-6">
                            <div class="input-group input-group-outline my-1 is-focused">
                                <label class="form-label">رقم الهاتف</label>
                                <input id="phone" name="phone" value="{{ $emploey->phone }}" type="text" class="form-control">
                            </div>
                        </div>
                    </div>
                    <div class="text-center">
                      <button type="submit" class="btn bg-gradient-primary w-50 my-4 mb-2 text-lg">
                        <span id="button_submit_text">تعديل</span>
                      </button>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@endsection

resources/views/admin/employees/employees.blade.php
@extends('admin.master')
@section('navbar-title', 'الموظفين')

@section('content')
<div class="row">
    <div class="col-12">
      <div class="card my-4">
        <div class="card-header p-0 position-relative mt-n4 mx-3 z-index-2">
          <div class="bg-gradient-primary shadow-primary border-radius-lg pt-4 pb-3">
            <h6 class="text-white text-capitalize pe-3">جدول الموظفين</h6>
          </div>
        </div>
        <div class="card-body px-0 pb-2">
            <div class="button_datatable px-2">
                <a href="{{route('dashboard.employees.create')}}" class="btn btn-success text-sm" id="add_new_user_button" type="button">
                    <i class="fa fa-plus"></i>
                    إضافة موظف جديد
                </a>

            </div>
            <div class="table-responsive p-0">
                <table class="table align-items-center mb-0 table-hover " style="width:100%">
                <thead>
                    <tr>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">الأسم الكامل</th>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">الشركة</th>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7">الإيميل</th>
                    <th class="text-uppercase text-secondary text-s font-weight-bolder opacity-7"> الهاتف </th>
                    <th class="text-secondary text-secondary text-s font-weight-bolder opacity-7">الاجراءات</th>
                    </tr>
                </thead>
                @foreach($employees as $emploey)
                    <tr>
                        <td>{{$emploey->first_name}} {{$emploey->last_name}}</td>
                        <td>{{$emploey->company->name}}</td>
                        <td>
                            @if ($emploey->email)
                            {{$emploey->email}}
                            @else
                                لا يوجد
                            @endif
                        </td>
                        <td>
                            @if ($emploey->phone)
                            {{$emploey->phone}}
                            @else
                                لا يوجد
                            @endif
                            </td>
                        <td>
                            {{-- Start For Edite --}}
                            <form method="GET" action="employees/{{ $emploey->id }}/edit" style="display: inline-block">

                                <button type="submit" class="btn btn-success">
                                    تعديل
                                </button>
                            </form>

                            {{-- Start For Delete --}}
                            <button type="button" class="btn btn-danger" data-bs-toggle="modal" data-bs-target="#deleteEmploey{{ $emploey->id }}">
                                حذف
                            </button>
                            <div class="modal fade" id="deleteEmploey{{ $emploey->id }}" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
                                <div class="modal-dialog">
                                  <div class="modal-content">
                                    <div class="modal-header">
                                      <h5 class="modal-title text-center" id="staticBackdropLabel">حذف معلومات الموظف</h5>
                                      <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                                    </div>
                                    <div class="modal-body">
                                        <form enctype="multipart/form-data" method="POST" action="employees/{{ $emploey->id }}" class="text-end ">
                                            @csrf
                                            @method('delete')
                                            <input type="hidden" name="id" value="{{ $emploey->id }}">
                                            <h4 class="text-black">هل أنت متأكد؟</h4>
                                    </div>
                                    <div class="modal-footer">
                                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">إغلاق</button>
                                      <button type="submit" class="btn btn-primary"> حذف</button>
                                    </div>
                                </form>
                                  </div>
                                </div>
                              </div>
                            {{-- End For Delete --}}
                        </td>
                    </tr>
                @endforeach
                </table>
                {{ $employees->links() }}
            </div>
        </div>
      </div>
    </div>
  </div>

  <!--     toast start     -->
  <div class="position-fixed top-0 start-0 p-lg-3" style="z-index: 11">
    <div class="toast fade hide p-2 mt-2 bg-gradient-info" role="alert" aria-live="assertive" id="infoToast" aria-atomic="true">
        <div class="toast-header bg-transparent border-0">
          <i class="material-icons text-white ms-2">notifications</i>
          <span class="ms-auto text-white font-weight-bold text-lg">اشعار</span>
          <i class="fas fa-times text-md text-white me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal light m-0">
        <div class="toast-body text-white text-lg">
          يتم الآن الحذف ....
        </div>
      </div>

      <div class="toast fade hide p-2 bg-white" role="alert" aria-live="assertive" id="successToast" aria-atomic="true">
        <div class="toast-header border-0">
          <i class="material-icons text-success ms-2">check</i>
          <span class="ms-auto font-weight-bold text-lg">نجاح</span>
          <i class="fas fa-times text-md me-3 cursor-pointer" data-bs-dismiss="toast" aria-label="Close"></i>
        </div>
        <hr class="horizontal dark m-0">
        <div class="toast-body text-lg">
         تمت العملية بنجاح
        </div>
      </div>

  </div>
  <!--     toast end     -->

@endsection